require("zer0.start_setup")
require("zer0.globals")
require("zer0.options")
require("zer0.lazy")
require("zer0.autocommands")
require("zer0.mapping")
require("zer0.diagnostics")
require("zer0.finish_setup")
