return {}
-- return {
--   "OXY2DEV/markview.nvim",
--   lazy = false,
--
--   priority = 49,
--
--   -- For blink.cmp's completion
--   -- source
--   -- dependencies = {
--   --     "saghen/blink.cmp"
--   -- },
--   keys = {
--     {
--       "<leader>mv",
--       function()
--         vim.cmd("Markview", "Toggle")
--       end,
--     },
--   },
-- }
